linters:
  enable-all: true
  disable:
    - golint                    # deprecated
    - interfacer                # deprecated
    - scopelint                 # deprecated
    - maligned                  # deprecated
    - gomoddirectives           # doesn't work with 1.17
    - wrapcheck                 # TODO
